# EXP_NAME: 'YOUR_EXPERIMENT_NAME'
RNG_SEED: 1
DATASET:
  NAME: PASCALVOC
  ROOT_DIR: '/home/ubuntu/mmdetection_od/mmdetection/data'
  VAL_RATIO: 0.1
  AUG_METHOD: 'hflip'
MODEL:
  TYPE: resnet50
  NUM_CLASSES: 20
OPTIM:
  TYPE: 'sgd'
  BASE_LR: 0.025
  LR_POLICY: cos
  LR_MULT: 0.1
  # STEPS: [0, 60, 120, 160, 200] 
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0003
  GAMMA: 0.1
TRAIN:
  SPLIT: train
  BATCH_SIZE: 100
  IM_SIZE: 32
  EVAL_PERIOD: 2
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
ACTIVE_LEARNING:
  INIT_L_RATIO: 0.
#  BUDGET_SIZE: 10
  # SAMPLING_FN: 'uncertainty'
  MAX_ITER: 5
  FINE_TUNE: False